// Mocks generated by Mockito 5.2.0 from annotations
// in to_do_app_manabie/test/features/todo/domain/usecases/get_to_do_list_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:to_do_app_manabie/core/failure/failure.dart' as _i5;
import 'package:to_do_app_manabie/features/todo/domain/entities/to_do_task.dart'
    as _i6;
import 'package:to_do_app_manabie/features/todo/domain/repositories/to_do_task_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ToDoTaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockToDoTaskRepository extends _i1.Mock
    implements _i3.ToDoTaskRepository {
  MockToDoTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ToDoTask>>> getListToDoTasks() =>
      (super.noSuchMethod(Invocation.method(#getListToDoTasks, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.ToDoTask>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.ToDoTask>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ToDoTask>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ToDoTask>> createToDoTask(
          String? name) =>
      (super.noSuchMethod(Invocation.method(#createToDoTask, [name]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.ToDoTask>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ToDoTask>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ToDoTask>>);
}
