// Mocks generated by Mockito 5.2.0 from annotations
// in to_do_app_manabie/test/features/todo/data/repositories/to_do_repository_impl.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:to_do_app_manabie/features/todo/data/datasources/to_do_task_local_data_source.dart'
    as _i4;
import 'package:to_do_app_manabie/features/todo/data/models/to_do_task_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeToDoTaskModel_0 extends _i1.Fake implements _i2.ToDoTaskModel {}

class _FakeUnit_1 extends _i1.Fake implements _i3.Unit {}

/// A class which mocks [ToDoTaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockToDoTaskLocalDataSource extends _i1.Mock
    implements _i4.ToDoTaskLocalDataSource {
  MockToDoTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ToDoTaskModel> getToDoTaskList() => (super.noSuchMethod(
          Invocation.method(#getToDoTaskList, []),
          returnValue: Future<_i2.ToDoTaskModel>.value(_FakeToDoTaskModel_0()))
      as _i5.Future<_i2.ToDoTaskModel>);
  @override
  _i5.Future<_i3.Unit> createToDo(String? name) =>
      (super.noSuchMethod(Invocation.method(#createToDo, [name]),
              returnValue: Future<_i3.Unit>.value(_FakeUnit_1()))
          as _i5.Future<_i3.Unit>);
}
